version: "3.2"

services:
  lighttpd:
    image: sebp/lighttpd:latest
    volumes:
      - type: bind
        source: ./docker/lighttpd/config
        target: /etc/lighttpd
    ports:
      - "31500:31337"
    command:
      - start.sh
    depends_on:
      - cgimap
      - web

  cgimap:
    image: cgimap:latest
    environment:
     - CGIMAP_HOST=db
     - CGIMAP_DBNAME=openstreetmap
     - CGIMAP_USERNAME=openstreetmap
     - CGIMAP_PASSWORD=openstreetmap
    command: /usr/local/bin/openstreetmap-cgimap --port=8000 --instances=30
    depends_on:
      - db

  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: openstreetmap
    volumes:
      - ./docker-db-data:/var/lib/postgresql/data
